### ISSUE TITLE
ko'rsatib qo'yilgan textga padding xato berganisz ya'ni text containerga yopishib turishi kerak , va buttonni o'rab turgan element ham yoq

### ISSUE THREAD

**Issue by Ali207614** [Sohibjon3412/Clerksy#2]
https://prnt.sc/1qdy4t9

**Comment by Sohibjon3412** [comment]
Textdagi paddingni to'g'irlab qo'ydim. Lekin biz xali inputni o'tmaganmiz. Javoxir aka shunchaki button qoldirib keteylar, keyin to'g'irlaymiz digandi
